version: "3.9"

services:
  api:
    build: .
    container_name: pythonwiki_api
    ports:
      - "7211:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pythonwiki_db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:
